#include <iostream.h>
#include <stdio.h>
#include <string>

void main()
{
string huruf;
 bool repeat = true;

 while (repeat)
    {
cout<<"huruf: ";
cin>>huruf;
if (huruf=="A")   {
      cout<<"									T"<<endl;}

          else

          if (huruf=="B")   {
      cout<<"									E"<<endl;}

            else

          if (huruf=="C")   {
      cout<<"									K"<<endl;}


          if (huruf=="D")   {
      cout<<"									N"<<endl;}


          if (huruf=="E")   {
      cout<<"									I"<<endl;}


          if (huruf=="F")   {
      cout<<"									F"<<endl;}


          if (huruf=="G")   {
      cout<<"									O"<<endl;}


          if (huruf=="H")   {
      cout<<"									R"<<endl;}


          if (huruf=="I")   {
      cout<<"									M"<<endl;}


          if (huruf=="J")   {
      cout<<"									A"<<endl;}


          if (huruf=="K")   {
      cout<<"									B"<<endl;}


          if (huruf=="L")   {
      cout<<"									C"<<endl;}


          if (huruf=="M")   {
      cout<<"									D"<<endl;}


          if (huruf=="N")   {
      cout<<"									G"<<endl;}


          if (huruf=="O")   {
      cout<<"									H"<<endl;}


          if (huruf=="P")   {
      cout<<"									J"<<endl;}


          if (huruf=="Q")   {
      cout<<"									L"<<endl;}

        
          if (huruf=="R")   {
      cout<<"									P"<<endl;}


          if (huruf=="S")   {
      cout<<"									Q"<<endl;}


          if (huruf=="T")   {
      cout<<"									S"<<endl;}


          if (huruf=="U")   {
      cout<<"									U"<<endl;}


          if (huruf=="V")   {
      cout<<"									V"<<endl;}


          if (huruf=="W")   {
      cout<<"									W"<<endl;}


          if (huruf=="X")   {
      cout<<"									X"<<endl;}


          if (huruf=="Y")   {
      cout<<"									Y"<<endl;}


          if (huruf=="Z")   {

      cout<<"									Z"<<endl;}


      cout << "Repeat? [1/2]" << endl;
        char answer;
        cin >> answer;
        repeat = answer == '1';
    }
    cout << "fuck you and goodbye!!!!" << endl;

      system("pause");

      }
