#include <iostream.h>
#include <stdio.h>
#include <string>

void main()
{
string huruf;
 bool repeat = true;

 while (repeat)
    {
cout<<"  ";
cin>>huruf;
if (huruf=="A")   {
      cout<<"D";}

          else

          if (huruf=="B")   {
      cout<<"I";}

            else

          if (huruf=="C")   {
      cout<<"A";}


          if (huruf=="D")   {
      cout<<"N";}


          if (huruf=="E")   {
      cout<<"O";}


          if (huruf=="F")   {
      cout<<"V";}


          if (huruf=="G")   {
      cout<<"B";}


          if (huruf=="H")   {
      cout<<"C";}


          if (huruf=="I")   {
      cout<<"E";}


          if (huruf=="J")   {
      cout<<"F";}


          if (huruf=="K")   {
      cout<<"G";}


          if (huruf=="L")   {
      cout<<"H";}


          if (huruf=="M")   {
      cout<<"J";}


          if (huruf=="N")   {
      cout<<"K";}


          if (huruf=="O")   {
      cout<<"L";}


          if (huruf=="P")   {
      cout<<"M";}


          if (huruf=="Q")   {
      cout<<"P";}

        
          if (huruf=="R")   {
      cout<<"Q";}


          if (huruf=="S")   {
      cout<<"R";}


          if (huruf=="T")   {
      cout<<"S";}


          if (huruf=="U")   {
      cout<<"T";}


          if (huruf=="V")   {
      cout<<"U";}


          if (huruf=="W")   {
      cout<<"W";}


          if (huruf=="X")   {
      cout<<"X";}


          if (huruf=="Y")   {
      cout<<"Y";}


          if (huruf=="Z")   {

      cout<<"Z";}



        repeat;
    }
    cout << "fuck you and goodbye!!!!" << endl;

      system("pause");

      }